apiVersion: v1
kind: Pod
metadata:
  generateName: evil-
  labels:
    app: hello
spec:
  containers:
  - name: main
    image: scothis/evil:s1tour
    env:
    - name: PORT
      value: "8080"
    - name: TARGET
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

