apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: blue-green-demo
spec:
  revisionTemplate:
    spec:
      container:
        image: gcr.io/knative-samples/knative-route-demo:green
        env:
          - name: T_VERSION
            value: "green"

---
apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: blue-green-demo
spec:
  traffic:
    - revisionName: blue-green-demo-00001
      percent: 100
    - revisionName: blue-green-demo-00002
      percent: 0
      name: v2
