apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: blue-green-demo
spec:
  revisionTemplate:
    spec:
      container:
        image: gcr.io/knative-samples/knative-route-demo:green
        env:
          - name: T_VERSION
            value: "green"
